# Generated by Django 5.0 on 2023-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_body_portfolio_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['title'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_detail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
